name: sw_core_package
description: The common core for all Flutter project
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.21.0
  logging: ^0.11.3+2
  logger: ^0.6.0
  shared_preferences: ^0.5.3+4
  progress_hud: ^1.1.0 # show loading
  fluttertoast: ^3.0.3
  fluro: ^1.4.0 # navigation
  intl: ^0.15.7 # localization
  dio: ^2.1.0 # HttpRequest
  url_launcher: ^5.0.2 # open browser
  flutter_device_type: ^0.2.0

  # google map
  google_maps_flutter: ^0.5.19+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
